# fly.toml app configuration file generated for blogposts-backend on 2024-08-06T16:56:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blogposts-backend'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
